### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/tmp/tmp913YKt0.5625.dat'

### ISSUE THREAD

**Issue by coderofsalvation** [ckald/Samplicity#11]
On this system:
On Alpine linux everything installs fine, however I'm getting this:

```
[root@LAPTOP-TORCIFES/home/leon/projects/samplepackfactory/out]  $ cat test.sfz
<group> ampeg_attack=0.0 ampeg_release=1 loop_mode=one_shot
<region> sample=wav\test-V127-O1-01-C1.wav lokey=58 hikey=58 pitch_keycenter=58
<region> sample=wav\test-V127-O1-02-C#1.wav lokey=59 hikey=59 pitch_keycenter=59
<region> sample=wav\test-V127-O1-03-D1.wav lokey=60 hikey=60 pitch_keycenter=60
<region> sample=wav\test-V127-O1-04-D#1.wav lokey=61 hikey=61 pitch_keycenter=61
<region> sample=wav\test-V127-O1-05-E1.wav lokey=62 hikey=62 pitch_keycenter=62
<region> sample=wav\test-V127-O1-06-F1.wav lokey=63 hikey=63 pitch_keycenter=63
<region> sample=wav\test-V127-O1-07-F#1.wav lokey=64 hikey=64 pitch_keycenter=64
<region> sample=wav\test-V127-O1-08-G1.wav lokey=65 hikey=65 pitch_keycenter=65
<region> sample=wav\test-V127-O1-09-G#1.wav lokey=66 hikey=66 pitch_keycenter=66
<region> sample=wav\test-V127-O1-10-A1.wav lokey=67 hikey=67 pitch_keycenter=67
<region> sample=wav\test-V127-O1-11-A#1.wav lokey=68 hikey=68 pitch_keycenter=68
<region> sample=wav\test-V127-O1-12-B1.wav lokey=69 hikey=69 pitch_keycenter=69
bash: .gitbranch: command not found
[root@LAPTOP-TORCIFES/home/leon/projects/samplepackfactory/out]  $ samplicity test.sfz test.xi
/usr/lib/python2.7/site-packages/scikits/audiolab/soundio/play.py:48: UserWarning: Could not import alsa backend; most probably, you did not have alsa headers when building audiolab
  warnings.warn("Could not import alsa backend; most probably, "
--------------------------------------------------------------------------------
Converting " test.sfz "
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/samplicity", line 11, in <module>
    load_entry_point('samplicity==0.5.1', 'console_scripts', 'samplicity')()
  File "build/bdist.linux-x86_64/egg/samplicity/__init__.py", line 13, in main
  File "build/bdist.linux-x86_64/egg/samplicity/samplicity.py", line 446, in main
  File "build/bdist.linux-x86_64/egg/samplicity/samplicity.py", line 394, in write_regions
IOError: [Errno 2] No such file or directory: '/tmp/tmp913YKt0.5625.dat'
```

further inspection:

```
[root@LAPTOP-TORCIFES/home/leon/projects/samplepackfactory/out]  $ ls /tmp/tmp*
/tmp/tmp913YKt0.578125.dat  /tmp/tmpSsLr7C0.546875.dat  /tmp/tmpvi4SaE0.546875.dat
/tmp/tmp913YKt0.59375.dat   /tmp/tmpSsLr7C0.5625.dat    /tmp/tmpvi4SaE0.5625.dat
/tmp/tmpEh5ndG0.609375.dat  /tmp/tmp_eRs1h0.5625.dat    /tmp/tmpxoI4pr0.59375.dat
/tmp/tmpPgiRip0.578125.dat  /tmp/tmp_eRs1h0.578125.dat  /tmp/tmpxoI4pr0.609375.dat
/tmp/tmpPgiRip0.59375.dat   /tmp/tmpvi4SaE0.53125.dat

/tmp/tmp04a9Lj:

/tmp/tmpUaoWaP:
bash: .gitbranch: command not found
[root@LAPTOP-TORCIFES/home/leon/projects/samplepackfactory/out]  $ ls -la *.xi
-rwxrwxrwx    1 leon     leon        435130 Nov  3 22:22 test.temp.xi
```

> Conclusion: it does write an .xi (partially) and it does write some files to tmp. 

Any ideas?

**Comment by coderofsalvation** [comment]
here you go: https://github.com/ckald/Samplicity/pull/12
