### ISSUE TITLE
SyntaxError: Non-ASCII character '\xc2'

### ISSUE THREAD

**Issue by negativerad** [ckald/Samplicity#8]
X:\Samplicity-master>python samplicity.py "Keys - Grand Piano.sfz" File "samplicity.py", line 3 SyntaxError: Non-ASCII character '\xc2' in file samplicity.py on line 3, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by negativerad** [comment]
I've tried this on Debian Wheezy and Windows 7, both with same error.

**Comment by ckald** [comment]
Hi there! Unexplainable how I missed this problem. Please, try now https://github.com/ckald/Samplicity/commit/9045dbf0192dee8886726aecceadc4292817afe9

**Comment by negativerad** [comment]
are there any dependencies libraries?

**Comment by ckald** [comment]
@negativerad 
No, this version shouldn't depend on anything. Although it is tested only on Python 2.

**Comment by ckald** [comment]
@negativerad 
Hi again! I pushed a new version. Could you please try to use it? It should be much better and even has normal install routine

**Comment by negativerad** [comment]
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

I guess i need to install setuptools :)

**Comment by ckald** [comment]
I didn't expect that :) And it seems that this installation recipe could be rather complicated. Please, try pip instead (http://pip.readthedocs.org/en/latest/installing.html)
